### ISSUE TITLE
drf-spectacular is confused about the field type

### ISSUE THREAD

**Issue by w00kie** [julianwachholz/django-sqids#3]
When running with [drf-spectacular](https://github.com/tfranzel/drf-spectacular) to generate OpenAPI schemas, the field type cannot be auto-inferred and the following error pops up in the logs when accessing Redoc or Swagger schema:

```
Error [IssueViewSet]: could not resolve model field "epics.Issue.sqid". Failed to resolve through serializer_field_mapping, get_internal_type(), or any override mechanism. Defaulting to "string"
```

It still works because it defaults to a string but I think that all that's required to get clean logs is add this method to the `SquidsField` class:

```python
def get_internal_type(self):
    return "CharField"
```

Will test and submit a PR momentarily.

**Comment by julianwachholz** [comment]
Closed via #4

**Comment by w00kie** [comment]
Can we have a new release with this fix included?

I've been pulling from my fork in the meantime but it would be nice to get this from the canonical package.

Cheers!

**Comment by julianwachholz** [comment]
@w00kie done!
