### ISSUE TITLE
New release - To work with Pydantic & Django-Ninja

### ISSUE THREAD

**Issue by areski** [julianwachholz/django-sqids#7]
I see that fixed was pushed already: https://github.com/julianwachholz/django-sqids/commit/72215eca6f63a2ad923a78ae26d83b77fdcdb4df#diff-63d04c63b5017bb9b21a5f20f3c2564452661915a225290dc766c53dee3bec4cR98

It would be nice that a new release is made, as many people may struggle to make it work with Django-Ninja or DRF.

Thanks!

**Comment by julianwachholz** [comment]
0.2.1 has been published :) Thank you for your patience!
